DWS.Web/Controllers/Api/PersonsController.cs
using AutoMapper;
using DWS.MovieLibrary.Domain.Dtos;
using DWS.MovieLibrary.Domain.Models;
using DWS.MovieLibrary.Web.Controllers.Api;
using DWS.PersonLibrary.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Http.Description;

namespace DWS.PersonLibrary.Web.Controllers.Api
{
    //[Authorize]
    [Route("api/Persons")]
    [ApiController]
    public class PersonsController : BaseController
    {
        #region Fields

        private readonly IPersonService _PersonService;
        private readonly IMapper _mapper;

        #endregion

        #region Constructors

        public PersonsController(IMapper mapper, IPersonService PersonService) : base()
        {
            _mapper = mapper;
            _PersonService = PersonService;
        }

        #endregion

        #region Person OPERTAIONS api

        [Route("all")]
        [HttpGet]
        [ResponseType(typeof(List<PersonDto>))]
        public async Task<IActionResult> GetAll()
        {

            var data = _PersonService.GetAll();
            var dataDto = _mapper.Map<List<PersonDto>>(data);

            if (dataDto != null)
            {
                return Ok(dataDto);
            }

            return NotFound();
        }

        [Route("add")]
        [HttpPost]
        [ResponseType(typeof(PersonDto))]
        public async Task<IActionResult> PostPerson(PersonDto PersonDTO)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                var Person = _mapper.Map<Person>(PersonDTO);

                _PersonService.CreatePerson(Person);

                _PersonService.Save();

                return Ok(PersonDTO);
            }
            catch (Exception error)
            {
                return BadRequest(error);
            }
        }

        [Route("getbyid/{PersonId}")]
        [HttpGet]
        [ResponseType(typeof(PersonDto))]
        public async Task<IActionResult> GetPerson(string PersonId)
        {
            var Person = _PersonService.GetPersonByID(PersonId);

            if (Person == null)
            {
                return NotFound();
            }

            var dataDto = _mapper.Map<PersonDto>(Person);

            return Ok(dataDto);
        }

        [Route("PersonsByFilter/{name}")]
        [HttpGet]
        [ResponseType(typeof(List<PersonDto>))]
        public async Task<IActionResult> GetPersonsByFilter(string name)
        {
            IEnumerable<Person> Persons = _PersonService.GetAll();

            if (Persons == null)
            {
                return NotFound();
            }


            if (!string.IsNullOrEmpty(name))
            {
                Persons = Persons.Where(t => t.FirstName.ToLower().Contains(name.ToLower())).ToList();
            }

            if (Persons == null)
            {
                return NotFound();
            }

            return Ok(Persons);

        }

        [Route("delete/{PersonId}")]
        [HttpDelete]
        [ResponseType(typeof(PersonDto))]
        public async Task<IActionResult> DeletePerson(string PersonId)
        {

            try
            {
                var PersonList = _PersonService.GetAll();

                var Person = PersonList.Where(m => m.ID == PersonId).SingleOrDefault();

                if (Person == null)
                {
                    return NotFound();
                }

                _PersonService.DeletePerson(PersonId);

                _PersonService.Save();

                return Ok($"Person with ID: {PersonId} has deleted");
            }
            catch (Exception error)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, error.Message);
            }
        }

        [Route("update/{PersonId}")]
        [ResponseType(typeof(PersonDto))]
        [HttpPut]
        public async Task<IActionResult> PutPerson(Guid PersonId, PersonDto PersonDTO)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            if (PersonId != PersonDTO.ID)
            {
                return BadRequest();
            }


            try
            {
                var Person = _mapper.Map<Person>(PersonDTO);

                _PersonService.UpdatePerson(Person);

                _PersonService.Save();

                var dataDTO = _mapper.Map<PersonDto>(PersonDTO);

                return Ok(dataDTO);
            }
            catch (Exception error)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError, $"Error : {error.Message}");
            }
        }

        #endregion
    }
}

DWS.Web/Controllers/MoviesController.cs
using DWS.MovieLibrary.Core.Extensions;
using DWS.MovieLibrary.Domain.Dtos;
using DWS.MovieLibrary.Web.Controllers.HttpClient;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace DWS.MovieLibrary.Web.Controllers
{

    public class MoviesController : CoreController
    {
        private readonly IApiClient _apiClient;
        public MoviesController(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public async Task<IActionResult> Index()
        {

            var result = await _apiClient.Get<List<MovieDto>>(GetBaseuRL(), "/api/movies/all");

            if (!result.HasError)
            {
                return View(result.Result);
            }
            else
            {
                return View("Error");

            }

        }

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }


        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MovieDto movie)
        {

            if (ModelState.IsValid)
            {

                try
                {
                    var postTask = await _apiClient.Create(GetBaseuRL(), "/api/movies/add", movie);

                    if (postTask.HasError)
                    {
                        if (postTask.Error.StatusCode == (int)HttpStatusCode.NotFound)
                        {
                            ModelState.AddModelError(string.Empty, $"");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, $"{postTask.Error.ReasonPhrase}");

                        }

                        return RedirectToAction("Create");
                    }
                }
                catch (Exception er)
                {
                    er.LogError();
                }

                return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }


        //GET - EDIT
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = await _apiClient.Get<MovieDto>(GetBaseuRL(), $"/api/Movies/getbyid/{id}");

            if (!result.HasError)
            {
                return View(result.Result);
            }
            else
            {
                return NotFound();
            }
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MovieDto movie)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var postTask = await _apiClient.Update(GetBaseuRL(), $"/api/Movies/update/{movie.ID}", movie);

                    if (postTask.HasError)
                    {
                        if (postTask.Error.StatusCode == (int)HttpStatusCode.NotFound)
                        {
                            ModelState.AddModelError(string.Empty, $"");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, $"{postTask.Error.ReasonPhrase}");

                        }
                        return View(movie);
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception er)
                {
                    er.LogError();
                }
            }
            return View(movie);

        }

        //GET - DELETE
        public async Task<IActionResult> DeleteRecord(string id, object data = null)
        {
            if (id == null || string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = await _apiClient.Get<MovieDto>(GetBaseuRL(), $"/api/Movies/getbyid/{id}");

            if (!result.HasError)
            {
                return View(result.Result);
            }
            else
            {
                return NotFound();
            }
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRecord(string id)
        {
            if (id == null || string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = await _apiClient.Delete<MovieDto>(GetBaseuRL(), $"/api/Movies/delete", id);

            if (!result.HasError)
            {
                return RedirectToAction("Index");
            }

            return NotFound();
        }

    }
}

DWS.Web/Controllers/PersonsController.cs
using DWS.MovieLibrary.Core.Extensions;
using DWS.MovieLibrary.Domain.Dtos;
using DWS.MovieLibrary.Web.Controllers;
using DWS.MovieLibrary.Web.Controllers.HttpClient;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace DWS.PersonLibrary.Web.Controllers
{

    public class PersonsController : CoreController
    {
        private readonly IApiClient _apiClient;
        public PersonsController(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public async Task<IActionResult> Index( string id = null)
        {

            var result = await _apiClient.Get<List<PersonDto>>(GetBaseuRL(), "/api/Persons/all");

            if (!result.HasError)
            {
                if (!string.IsNullOrEmpty(id))
                {
                    return View(result.Result.Where( m => m.MovieID == id));
                }
                return View(result.Result);
            }
            else
            {
                return View("Error");

            }

        }

        //GET - CREATE
        public async  Task<IActionResult> Create()
        {
            var Person = new PersonDto();

            var result = await _apiClient.Get<List<MovieDto>>(GetBaseuRL(), "/api/movies/all");

            if (!result.HasError)
            {
                Person.MovieList = result.Result.Select(m => new MovieLibrary.Domain.Models.DropDownItem { Text = m.Name, Value = m.ID }).ToList();
            }
            return View(Person);
        }


        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonDto Person)
        {

            if (ModelState.IsValid)
            {

                try
                {
                    var postTask = await _apiClient.Create(GetBaseuRL(), "/api/Persons/add", Person);

                    if (postTask.HasError)
                    {
                        if (postTask.Error.StatusCode == (int)HttpStatusCode.NotFound)
                        {
                            ModelState.AddModelError(string.Empty, $"");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, $"{postTask.Error.ReasonPhrase}");

                        }

                        return RedirectToAction("Create");
                    }
                }
                catch (Exception er)
                {
                    er.LogError();
                }

                return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }


        //GET - EDIT
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = await _apiClient.Get<PersonDto>(GetBaseuRL(), $"/api/Persons/getbyid/{id}");

            if (!result.HasError)
            {
                return View(result.Result);
            }
            else
            {
                return NotFound();
            }
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PersonDto Person)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var postTask = await _apiClient.Update(GetBaseuRL(), $"/api/Persons/update/{Person.ID}", Person);

                    if (postTask.HasError)
                    {
                        if (postTask.Error.StatusCode == (int)HttpStatusCode.NotFound)
                        {
                            ModelState.AddModelError(string.Empty, $"");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, $"{postTask.Error.ReasonPhrase}");

                        }
                        return View(Person);
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception er)
                {
                    er.LogError();
                }
            }
            return View(Person);

        }

        //GET - DELETE
        public async Task<IActionResult> DeleteRecord(string id, object data = null)
        {
            if (id == null || string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = await _apiClient.Get<PersonDto>(GetBaseuRL(), $"/api/Persons/getbyid/{id}");

            if (!result.HasError)
            {
                return View(result.Result);
            }
            else
            {
                return NotFound();
            }
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRecord(string id)
        {
            if (id == null || string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = await _apiClient.Delete<PersonDto>(GetBaseuRL(), $"/api/Persons/delete", id);

            if (!result.HasError)
            {
                return RedirectToAction("Index");
            }

            return NotFound();
        }

    }
}

DWS.Web/Views/Persons/Create.cshtml
@model DWS.MovieLibrary.Domain.Dtos.PersonDto

<div class="header">
    <h2 class="text-center my-5">Movie Library</h2>
</div>

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Person</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" class="form-control" />
                        @*<span asp-validation-for="PostalCode" class="text-danger"></span>*@
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" class="form-control" />
                        @*<span asp-validation-for="AnnulIncome" class="text-danger"></span>*@
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Gender"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Gender" class="form-control" asp-items="@Html.GetEnumSelectList<DWS.MovieLibrary.Domain.Models.Enum.Gender>()"></select>
                        @*<span asp-validation-for="AnnulIncome" class="text-danger"></span>*@
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Role"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="Role" class="form-control" asp-items="@Html.GetEnumSelectList<DWS.MovieLibrary.Domain.Models.Enum.Role>()"></select>
                        @*<span asp-validation-for="AnnulIncome" class="text-danger"></span>*@
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="MovieList"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="MovieID" class="form-control" asp-items="@(new SelectList(Model.MovieList, "Value", "Text"))">
                            <option value="">--Select--</option>

                        </select>
                        @*<span asp-validation-for="AnnulIncome" class="text-danger"></span>*@
                    </div>

                </div>



                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Add" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-list-ul"></i> View Persons</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
                        <partial name="_ValidationScriptsPartial" />
    }

}

DWS.Web/Views/Persons/DeleteRecord.cshtml
@model DWS.MovieLibrary.Domain.Dtos.PersonDto

<div class="header">
    <h2 class="text-center my-5">Movie Library</h2>
</div>

<form method="post" asp-action="DeleteRecord">

    <input asp-for="ID" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Person</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" class="form-control" disabled />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" class="form-control" disabled />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Gender"></label>
                    </div>
                    <div class="col-8">
                        <td class="form-control">@Html.Raw(DWS.MovieLibrary.Core.Helpers.OtherHelpers.GetEnumValue<@DWS.MovieLibrary.Domain.Models.Enum.Gender>(Model.Gender))</td>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Role"></label>
                    </div>
                    <div class="col-8">
                        <td class="form-control">@Html.Raw(DWS.MovieLibrary.Core.Helpers.OtherHelpers.GetEnumValue<@DWS.MovieLibrary.Domain.Models.Enum.Role>(Model.Role))</td>
                    </div>

                </div>

               

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-list-ul"></i> View Persons</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
                        <partial name="_ValidationScriptsPartial" /> }

}

DWS.Web/Views/Persons/Edit.cshtml
@model DWS.MovieLibrary.Domain.Dtos.PersonDto

<div class="header">
    <h2 class="text-center my-5">Movie Library</h2>
</div>

<form method="post" asp-action="Edit">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Person</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" class="form-control" />
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" class="form-control" />
                    </div>

                </div>

                <div class="form-group row">

                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Gender"></label>
                        </div>
                        <div class="col-8">
                            <select asp-for="Gender" class="form-control" asp-items="@Html.GetEnumSelectList<DWS.MovieLibrary.Domain.Models.Enum.Gender>()"></select>
                        </div>

                    </div>

                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="Role"></label>
                        </div>
                        <div class="col-8">
                            <select asp-for="Role" class="form-control" asp-items="@Html.GetEnumSelectList<DWS.MovieLibrary.Domain.Models.Enum.Role>()"></select>
                        </div>

                    </div>


                    <div class="form-group row">
                        <div class="col-4">
                            <label asp-for="MovieList"></label>
                        </div>
                        <div class="col-8">
                            <select asp-for="MovieID" class="form-control" asp-items="@(new SelectList(Model.MovieList, "Value", "Text"))">
                                <option value="">--Select--</option>

                            </select>
                        </div>

                    </div>


                    <div class="form-group row">
                        <div class="col-8 offset-4 row">

                            <div class="col">
                                <input type="submit" class="btn btn-info w-100" value="Update" />
                            </div>
                            <div class="col">
                                <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-list-ul"></i> Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    @* Keep this empty *@
                </div>
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
                        <partial name="_ValidationScriptsPartial" />
    }

}

DWS.Web/Views/Persons/Index.cshtml
@model IEnumerable<DWS.MovieLibrary.Domain.Dtos.PersonDto>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Persons</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Persons" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Add New Person
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                FirstName
            </th>
            <th>
                LastName
            </th>
            <th>
                Gender
            </th>
            <th>
                Role
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
<tr>
    <td width="20%">@obj.FirstName</td>
    <td width="20%">@obj.LastName</td>
    <td width="20%">@Html.Raw(DWS.MovieLibrary.Core.Helpers.OtherHelpers.GetEnumValue<@DWS.MovieLibrary.Domain.Models.Enum.Gender>(@obj.Gender))</td>
    <td width="20%">@Html.Raw(DWS.MovieLibrary.Core.Helpers.OtherHelpers.GetEnumValue<@DWS.MovieLibrary.Domain.Models.Enum.Role>(@obj.Role))</td>


    <td class="text-center">
        <div class="w-75 btn-group" role="group">
           

            <a asp-controller="Persons" asp-route-Id="@obj.ID" asp-action="DeleteRecord" class="btn btn-danger mx-2">
                <i class="far fa-trash-alt"></i>
            </a>
        </div>
    </td>
</tr>}
    </tbody>
</table> }
else
{
<p> No Person(s) exist.</p>}


    <div class="col-6 text-left">
        <a asp-controller="Movies" asp-action="Index" class="btn btn-primary"> Back</a>
    </div>

</div>